# -*- coding: utf-8 -*-
"""ApproximateInference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0Tod1ybnSuvusJjQJMbTSl1ckg3C1qR
"""

# approximate inference in Bayes Networks
# Michael Branicky, 2020-04-01

# Example 1: Compute P(-g,-m,-b, l)
# Example 2: Compute P(-l | -m)

from random import random

TRIALS = 10**6

evidence = 0
query = 0
pall = []
pdenomall = []
joint_observed = 0
pjointall = []

for trial in range(1,TRIALS+1):
    randB, randE, randA, randJ, randM= ( random() for i in range(5) )
    B = (randB < 0.1)
    E = (randE < 0.2)
   #B and E True
    if E and B:
        A = (randA < .98)
        if A:  
            J = (randJ < .95)
            M = (randM < .7)
        else:
            J = (randJ < .01)
            M = (randM < .01)
    #B and not E
    elif not E and B:
        A = (randA < .95)
        if A:  
            J = (randJ < .95)
            M = (randM < .7)
        else:
            J = (randJ < .01)
            M = (randM < .01)
    elif E and not B:
        A = (randA < .29)
        if A:  
            J = (randJ < .95)
            M = (randM < .7)
        else:
            J = (randJ < .01)
            M = (randM < .01)
    #Not B and Not E
    else:
        A = (randA < .001)
        if A:  
            J = (randJ < .95)
            M = (randM < .7)
        else:
            J = (randJ < .01)
            M = (randM < .01)
    # DIRECT SAMPLING FOR JOINT PROB. ESTIMATE
    if (J, M, B, E) == (False, False, True, True):
        joint_observed += 1
        pjointall.append(joint_observed/trial)
    # REJECTION SAMPLING: ONLY PROCESS IF EVIDENCE True
    """
    if D:
        evidence += 1
        if A:
            query += 1
        p = query/evidence
        pall.append(p)
    #pdenom = evidence/trial
    """
print("P(-j,-m, b, e) ~=", pjointall[-1])
#print("      P(A|D) ~=", pall[-1])
#print("         P(-m) ~=", pdenomall[-1])
#print("      P(-l,-m) ~=", pall[-1]*pdenomall[-1])

